export function renderHeader(): string {
  return `#!/bin/sh
# This installer was generated by installerer.
# <https://github.com/tooppoo/installerer>
# Review this script before running it.
# This generated installer is provided as-is, without any warranty.
# The target repository, release assets, and installed software remain subject to their own licenses.
set -u

if [ "\${DEBUG:-}" = "1" ]; then
  set -x
fi

`;
}
